AllCops: 
  EnabledByDefault: false 
  TargetRubyVersion: 2.7.0 
  Exclude: 
    - 'bin/**/*' 
    - 'config/**/*' 
    - 'coverage/**/*' 
    - 'db/**/*' 
    - 'libs/**/*' 
    - 'log/**/*' 
    - 'node_modules/**/*' 
    - 'public/**/*' 
    - 'script/**/*' 
    - 'storage/**/*' 
    - 'tmp/**/*' 
    - 'vendor/**/*' 
    - 'config.ru' 
    - 'Rakefile'
